// generated by Fast Light User Interface Designer (fluid) version 1.0107f

#ifndef WIDGETPDIAL_h
#define WIDGETPDIAL_h
#include <FL/Fl_Dial.H>
#include "TipWin.h"


class WidgetPDial:public Fl_Dial
{
    public:
        WidgetPDial(int x, int y, int w, int h, const char *label = 0);
        ~WidgetPDial();
        int handle(int event);
        void draw();
        void pdialcolor(int r, int g, int b);
        void tooltip(const char *c);
	void set_transform(float scale = 1.0, float offset = 0.0);
	float transform(float x);
        void setRounding(unsigned int digits = 0);
        float reset_value;
    protected:
        bool integer_step;
    private:
        void getPos();
        void resetPos();
        double oldvalue;
        int old_y;
        bool   pos;
        bool   textset;
        class TipWin * tipwin;
        float value_offset;
        float value_scale;
        int mod_state;
};
#endif
