#!/bin/bash

if [ -f "$(dirname ${0})/carla-utils.pc" ]; then
    cd "$(dirname ${0})/.."
    INSTALL_LIBDIR="./bin"
else
    INSTALL_PREFIX="X-PREFIX-X"
    INSTALL_LIBDIR="${INSTALL_PREFIX}/lib/carla"
fi

exec "${INSTALL_LIBDIR}/carla-bridge-native" internal "" carlapatchbay
