#!/bin/sh

PYTHON=$(which python3 2>/dev/null)

if [ ! -f ${PYTHON} ]; then
  PYTHON=python
fi

if [ "$1" = "--gdb" ]; then
  PYTHON="gdb --args $PYTHON"
fi

INSTALL_PREFIX="X-PREFIX-X"
export PATH="$INSTALL_PREFIX"/lib/carla:$PATH
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla_settings.py --with-libprefix="$INSTALL_PREFIX" "$@"
