#!/bin/bash

PYTHON=$(which python3 2>/dev/null)

if [ ! -f ${PYTHON} ]; then
  PYTHON=python
fi

INSTALL_PREFIX="X-PREFIX-X"
export CARLA_LIB_PREFIX="$INSTALL_PREFIX"
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla_modgui.py "$@"
