#!/bin/sh

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

INSTALL_PREFIX="X-PREFIX-X"
export CARLA_LIB_PREFIX="$INSTALL_PREFIX"
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla_modgui.py "$@"
