#!/bin/bash

set -e

cd $(dirname ${0})
cd ..

CARLA_DIR=$(pwd)
DISTRHO_PORTS_DIR=/tmp/distrho-ports-carla

rm -rf ${DISTRHO_PORTS_DIR}
git clone git@github.com:DISTRHO/DISTRHO-Ports.git ${DISTRHO_PORTS_DIR} --depth=1

CARLA_MODULES_DIR=${CARLA_DIR}/source/modules
JUCE_MODULES_DIR=${DISTRHO_PORTS_DIR}/libs/juce7/source/modules

MODULES=("juce_audio_basics juce_audio_devices juce_audio_processors juce_core juce_data_structures juce_events juce_graphics juce_gui_basics juce_gui_extra")

for M in ${MODULES}; do
  echo ${CARLA_MODULES_DIR}/${M};
  rm -f ${CARLA_MODULES_DIR}/${M}/juce_*
  rm -rf ${CARLA_MODULES_DIR}/${M}/{a..z}*
  cp -r -v ${JUCE_MODULES_DIR}/${M}/* ${CARLA_MODULES_DIR}/${M}/
  rm ${CARLA_MODULES_DIR}/${M}/juce_*.mm
done

find ${CARLA_MODULES_DIR} -name juce_module_info -delete

rm -rf ${CARLA_MODULES_DIR}/../includes/vst3sdk
mv ${CARLA_MODULES_DIR}/juce_audio_processors/format_types/VST3_SDK ${CARLA_MODULES_DIR}/../includes/vst3sdk
rm -rf ${CARLA_MODULES_DIR}/../includes/vst3sdk/*.pdf

# rm -rf ${DISTRHO_PORTS_DIR}
