#!/usr/bin/make -f
# Makefile for utils #
# ------------------ #
# Created by falkTX
#

include ../../Makefile.mk

# --------------------------------------------------------------

all:

clean:

debug:
	$(MAKE) DEBUG=true
