#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2011-2024 Filipe Coelho <falktx@falktx.com>
# SPDX-License-Identifier: GPL-2.0-or-later

# ----------------------------------------------------------------------------------------------------------------------
# Imports (Custom Stuff)

from carla_host import *

# ----------------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    import resources_rc

    # ------------------------------------------------------------------------------------------------------------------
    # Read CLI args

    initName, libPrefix = handleInitialCommandLineArguments(__file__ if "__file__" in dir() else None)

    # ------------------------------------------------------------------------------------------------------------------
    # App initialization

    app = CarlaApplication("Carla2-Multi-Client", libPrefix)

    # ------------------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # ------------------------------------------------------------------------------------------------------------------
    # Init host backend

    os.environ["CARLA_NSM_NAME"] = "Carla-Multi-Client"

    host = initHost(initName, libPrefix, False, False, True)
    host.audioDriverForced = "JACK"
    host.processMode       = ENGINE_PROCESS_MODE_MULTIPLE_CLIENTS
    host.processModeForced = True
    host.transportMode     = ENGINE_TRANSPORT_MODE_JACK
    loadHostSettings(host)

    # ------------------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = HostWindow(host, True)

    # ------------------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.showIfNeeded()

    # ------------------------------------------------------------------------------------------------------------------
    # App-Loop

    app.exit_exec()
