#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Carla plugin host
# Copyright (C) 2011-2013 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the GPL.txt file

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

try:
    from PyQt5.QtCore import QTimer
    from PyQt5.QtWidgets import QApplication
except:
    from PyQt4.QtCore import QTimer
    from PyQt4.QtGui import QApplication

# ------------------------------------------------------------------------------------------------------------
# Imports (Custom Stuff)

from carla_host import *
from carla_rack import CarlaRackW

# ------------------------------------------------------------------------------------------------------------
# Main Window

class CarlaMiniW(HostWindow):
    def __init__(self, parent=None):
        HostWindow.__init__(self, parent)
        #self.ui =  ui_carla.Ui_CarlaMainW()
        #self.ui.setupUi(self)

        Carla.host.engine_init("JACK", "Carla")

        self.fContainer = CarlaRackW(self)
        self.setCentralWidget(self.fContainer)

        self.init()

        QTimer.singleShot(0, self.slot_pluginAdd)

    def closeEvent(self, event):
        Carla.host.engine_close()
        HostWindow.closeEvent(self, event)

    @pyqtSlot()
    def slot_pluginAdd(self):
        dialog = PluginDatabaseW(self)

        if not dialog.exec_():
            return

        btype    = dialog.fRetPlugin['build']
        ptype    = dialog.fRetPlugin['type']
        filename = dialog.fRetPlugin['binary']
        label    = dialog.fRetPlugin['label']

        if not Carla.host.add_plugin(btype, ptype, filename, None, label, c_nullptr):
            CustomMessageBox(self, QMessageBox.Critical, self.tr("Error"), self.tr("Failed to load plugin"), cString(Carla.host.get_last_error()), QMessageBox.Ok, QMessageBox.Ok)
            return

        self.fContainer.addPlugin(0)

# ------------------------------------------------------------------------------------------------------------
# --------------- main ------------------

if __name__ == '__main__':
    # App initialization
    app = QApplication(sys.argv)
    app.setApplicationName("Carla")
    app.setApplicationVersion(VERSION)
    app.setOrganizationName("falkTX")
    app.setWindowIcon(QIcon(":/scalable/carla.svg"))

    libName = carla_library_filename
    libPath = os.path.join(carla_library_filename.replace(carla_libname, ""), "..", "modules", "carla_native", "resources")

    # Init backend
    print("libName:", libName, ":", carla_libname)
    Carla.host = Host(libName)

    Carla.host.set_engine_option(OPTION_PROCESS_NAME, 0, "carla")
    Carla.host.set_engine_option(OPTION_PATH_RESOURCES, 0, libPath)

    # Create GUI and start engine
    Carla.gui = CarlaMiniW()

    # Show GUI
    Carla.gui.show()

    # App-Loop
    ret = app.exec_()

    # Destroy GUI
    tmp = Carla.gui
    Carla.gui = None
    del tmp

    # Exit properly
    sys.exit(ret)
