name: dpf

on: [push, pull_request]

env:
  PAWPAW_SKIP_LTO: 1
  PAWPAW_SKIP_TESTS: 1

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-x86_64]
        # TODO: add PawPaw bootstrap type
        # linux-arm64, linux-armhf, linux-i686, linux-riscv64,
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true
          release: false

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal, macos-universal-10.15]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: fake dpf script
        run: |
          mkdir -p dpf/utils
          ln -s $(which ls) dpf/utils/package-osx-bundles.sh
          touch carla-macOS.pkg
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true
          release: false

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          pawpaw: true
          release: false

  # NOTE disabled for now
  # lv2lint does not allow to differentiate exposed features for multiple plugins in a single binary
  # (e.g. plugin A uses worker while plugin B does not, but they come from the same binary)
  # see https://github.com/falkTX/Carla/actions/runs/7389992205/job/20103997236
  #pluginval:
    #runs-on: ubuntu-20.04
    #steps:
      #- uses: actions/checkout@v4
        #with:
          #submodules: recursive
      #- uses: distrho/dpf-makefile-action@v1
        #with:
          #target: pluginval
          #pawpaw: true

  source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: source
          release: false
